# Generated by Django 4.2.7 on 2024-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_restaurant_address_restaurant_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='buyer/default_image.jpg', null=True, upload_to='restaurant_images'),
        ),
    ]
